name: 'Create Branch From a Specific Tag'
description: 'Create Branch From Specific Tag'
author: "Cloud Posse"

inputs:
  branch:
    description: 'The branch to create'
    default: 'release'
  from:
    description: 'Provide the tag number ex:- v0.0.7 or branch name i.e develop'
    required: true

runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: 'git-branch'
  color: 'black'
